version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_NAME}      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGA_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${PGA_PW}"
    ports:
      - "54321:80"
    depends_on:
      - postgres